### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by Internetpirate** [AnonymousDeveloper4201337/Toontown-Single-Player#1]
why this no work i click "start-game.bat" and give me eror "no file named main.py"

pls fix halp thank

**Comment by MacandWindows** [comment]
**we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.** **we are team woof, expect us.**

**Comment by Internetpirate** [comment]
hwut? team woof? can tey fix tah isue?

**Comment by MacandWindows** [comment]
ask mgracer48 he is a great and hard working indie developer

**Comment by Internetpirate** [comment]
@AnonymousDeveloper4201337 help pls

**Comment by AnonymousDeveloper4201337** [comment]
this game is still a wip
check back when  i announce that u can get into playgrounds

**Comment by AnonymousDeveloper4201337** [comment]
or u can contribute to the code
